fileVersion: 1
id: "37"
mappingDefinitions:
  FLOWER:
    database: GARDEN_PLANTS1
    schema: FLOWER
  FRUITS:
    database: GARDEN_PLANTS1
    schema: FRUITS
  VEGGIES:
    database: GARDEN_PLANTS1
    schema: VEGGIES
name: DWW_Environment
type: Environment
